name: Publish Python Package to PyPI

on:
  release:
    types: [published] # Run only when a release is published

permissions:
  # IMPORTANT: This permission is needed for uv publish to authenticate with PyPI using OIDC
  id-token: write

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest # Or use a matrix for multi-platform wheels

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1

      - name: Build distributions
        run: uv build --no-sources
        # Using --no-sources is recommended for publishing builds
        # to ensure it works without project-specific index configs.

      - name: Publish distributions to PyPI
        run: uv publish
        # No --token or other auth needed; uses OIDC via id-token permission
        # uv publish will automatically find artifacts in dist/ 